---
title: "What's Enough?"
author: "Lauren Low"
output: html_document
---


[Apple commercials](https://www.youtube.com/watch?v=b3VcGKv9Cfw) look diverse.  Kendrick Lamar, black musical talent, is front and center.  Gloria Steinem, feminist icon, appears at her desk.  Takashi Murakami, Japanese contemporary artist, speaks to a crowd. RuPaul, gay actor and influencer of color, sits beside his MacBook Pro.  

These advertisements are stylish with black and white photos, upbeat music and inspiring voice overs.  Don’t be fooled though.  This is called [diversity branding](https://uxdesign.cc/how-diversity-branding-hurts-diversity-66816cbd2d67). 

In the 1960s diversity branding didn’t exist.  Including people of all races, genders and sexualities wasn’t in fashion and consequently those who were anything but white and male were left in the shadows.  Christine Darden, the topic of [Data Feminism’s](https://data-feminism.mitpress.mit.edu/pub/frfa9szd/release/4) introduction and a black woman who started at NASA in 1967, knows all about being in the shadows.  

Darden was a human computer in NASA’s Advanced Computing division, where almost all the other employees were white women.  She was one of the mathematicians behind the Apollo 11 mission, calculating flight paths by hand.  She was also supervised by men who didn’t bother recognize her accomplishments, let alone learn her name.  As a black woman under white gaze, Darden was discriminated against, to say the least. 

Watching man after man receive job promotions, Darden began to question why women, herself included, weren’t rising the ranks at the same rate.  When she approached the chief of her division on this topic, he shot her down.  With the help of a colleague in the Equal Opportunity Office and some hard numbers, Darden was able to convince her supervisor that there was a problem: women were being systematically oppressed at NASA.  

Authors [Catherine D’Ignazio](https://data-feminism.mitpress.mit.edu/user/catherine-dignazio) and [Lauren Klein](https://data-feminism.mitpress.mit.edu/user/lauren-klein) go on to discuss the [lack of intersectionality](https://www.vox.com/2018/3/20/16955588/feminism-waves-explained-first-second-third-fourth) within second wave feminism.  While new waves of feminism have begun since the 1960s, white women still have the upper hand over women of color.  NASA is still male dominated.  Only [28% of executive senior leadership and 16% of senior scientists](https://www.washingtonpost.com/technology/2019/11/26/nasa-was-year-woman-yet-women-still-are-big-minority-space-agency/) at NASA are women.  The agency [didn’t report](https://www.nasa.gov/sites/default/files/atoms/files/fy_2018_nasa_md-715_report_508.pdf) the proportion of women of color in these roles.  

The lessons are bi-fold: organizations need to make substantial efforts to employ minorities and minorities need to receive positive recognition for their work.  Women of color hoping to pursue a career in data science have few others to look up to.  Having women make up a mere third of NASA employees isn’t enough.  Forcing showy commercials about diversity onto the public isn’t enough.  Making vaguely progressive statements about a corporate stance on the Black Lives Matter movement isn’t enough.  Giving minorities a platform and treating them as equals is enough.  