---
title: "blog 4"
output: html_document
author: Lauren Low
---

For each category within the [MeyersBriggs personality test](https://www.16personalities.com/) I stray far from the extremes.  I’m 59% extroverted and 41% introverted.  I’m 52% orderly and 48% spontaneous.  When taking in information I apparently use sight, taste, touch, etc. 54% of the time and the other 46% comes intuitively (whatever that means).  The one exception is that I supposedly make decisions based on values rather than rational and logical thought – I’m 71% feeling and 39% thinking to be exact.  

Most of these labels–thinking and feeling, especially–don’t *feel* mutually exclusive to me.  

In classes like [Thinking Through Race](https://sophia.smith.edu/idp102-sp21/), I’m intrigued by the notion that race is a social construct and has been perpetuated systematically by society and science.  In Feminist Journalism I enjoyed discourse centered around the underlying presence of gender in economics, vaccine hesitancy and Northampton coffee shops.  Sometimes I like to ponder where my future job will be and what sort of work I will be doing.  I imagine myself doing statistics for a cause and saving the world from a data disaster.

My academic experiences and perceptions of the future are not separate from the way I internalize.  When I changed my pronouns from “she/her” to “she and they” on Zoom, I felt like I was wearing a tight wool sweater in 90deg heat.  Submitting weekly exit tickets for Thinking Trough Race makes me reflect on how I *feel* when fitting into racial roles and fulfilling or challenging certain tropes.  I *feel* fearful that I’ll be unemployed for months or years after I graduate.  Or worse, I’ll settle for job that I despise for the sole purpose of being financially independent from my parents.  All these feelings are not in absence of methodically thinking through academic topics.  My lived experiences have a direct line into the way I process what I’m learning.  

This is instinctual to humans.  Not being able to separate thoughts from emotions is what differentiates a person from a computer (among other things).  Data are one of the many the crossroads between thinking and feeling.  As students studying data science, we know better than most that data are sandwiched between logical algorithms and social impact.  As Klein and D’ignazio suggest, it only makes sense to acknowledge emotions in quantitative conversations.  After all, there’s *feelings* behind the numbers. 
