---
title: "blog 5"
output: html_document
author: Lauren Low
---

There are ten principles of [radical acceptance](https://www.skylandtrail.org/accepting-reality-using-dbt-skills/#:~:text=Radical%20acceptance%20is%20when%20you,in%20a%20cycle%20of%20suffering).  

1.	Observe that you’re fighting reality.  
2.	Remember that unpleasant reality can’t be changed.  
3.	Remember the causes of reality.  
4.	Accept yourself.  
5.	Understand the different between how you would behave if you accepted and did not accept the facts.  
6.	Rehearse accepting what you believe to be unacceptable.  
7.	Be in tune with your body as you’re doing all of this.  
8.	Allow negative feelings to arise.  
9.	Acknowledge life is worth living even when there’s pain.  
10.	Make a pros and cons list if you resist any of the above.  

This, I’ve learned, can help me independently sort through most levels of my own angsty wallowing.  Example?  I feel queasy when I have to label my gender or categorize myself into a binary for others to feel comfortable.  Solution:  I can ride out the stomach churn and understand that just because I don’t fit into a box society has created doesn’t mean my thoughts and feelings are invalid.  I accept that I don’t feel like a single gender all the time and that society may not understand this.  When I’m not attune to this, I easily get frustrated, but I can empathize with people who may not understand the gender spectrum.  Even though talking to these people is difficult and can cause pain, my feelings and explanations are worth their understanding.  

Categorizing is not built on a foundation of emotional understanding.  Categories require structure while feelings demand flexibility.  Yet we continue to categorize without taking into account feelings because classification breeds familiarity.  

[D’Ignazio and Klein](https://data-feminism.mitpress.mit.edu/pub/h1w0nbqp/release/2?readingCollection=0cd867ef) shrug their shoulders toward the end of Chapter 4.  Should we keep categorization the way it is?  Should we change the way we think about categorizing people?  They eventually land on the fact that people are much more than the boxes we place them in.  This is true, but systems still function on grouping people.  Since this is the reality, the folks being categorized – as well as those who are ignored because they don’t fit – need a way to cope.  And by now you’ve probably guessed, I think radical acceptance is the way.  
